name: Build Rio for Fedora 39

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: fedora:39

    steps:
      - name: Install dependencies
        run: |
          dnf install -y git rust cargo make gcc curl mesa-libEGL-devel mesa-libGL-devel vulkan-loader

      - name: Checkout Rio
        uses: actions/checkout@v4

      - name: Build
        run: |
          cargo build --release

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: rio-fedora39
          path: target/release/rio
