name: Build Rio for Fedora 39

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: fedora:39

    steps:
      - name: Install system dependencies
        run: |
          dnf update -y
          dnf install -y \
            git curl gcc gcc-c++ make \
            fontconfig-devel libxkbcommon-devel \
            mesa-libEGL-devel mesa-libGL-devel vulkan-loader \
            cmake pkgconfig

      - name: Install latest Rust (via rustup)
        run: |
          curl https://sh.rustup.rs -sSf | sh -s -- -y
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
          source "$HOME/.cargo/env"
          rustup show

      - name: Checkout Rio source
        uses: actions/checkout@v4

      - name: Build Rio
        run: |
          source "$HOME/.cargo/env"
          cargo build --release

      - name: Upload Rio binary
        uses: actions/upload-artifact@v4
        with:
          name: rio-fedora39
          path: target/release/rio
